config/routes.rb
Rails.application.routes.draw do
  resources :points

  devise_for :users
  get 'mappoint/create', as: 'user_root'

   root 'mappoint#create'

end

app/models/point.rb
class Point < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mappoint_controller.rb
class MappointController < ApplicationController
  def create
  end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  before_action :set_point, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @points = Point.all
    respond_with(@points)
  end

  def show
    respond_with(@point)
  end

  def new
    @point = Point.new
    respond_with(@point)
  end

  def edit
  end

  def create
    @point = Point.new(point_params)
    @point.save
    respond_with(@point)
  end

  def update
    @point.update(point_params)
    respond_with(@point)
  end

  def destroy
    @point.destroy
    respond_with(@point)
  end

  private
    def set_point
      @point = Point.find(params[:id])
    end

    def point_params
      params.require(:point).permit(:coord, :usermail)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mappoint_helper.rb
module MappointHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railbox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

</body>
</html>

app/views/mappoint/create.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head><title></title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
      <meta charset="utf-8"/>
    <style type="text/css">
      html { height: 100% }
      body { height: 100%; margin: 0; padding: 0 }
      #map_canvas { height: 80% }
      #panel {
        position: absolute;
        top: 5px;
        left: 50%;
        margin-left: -180px;
        z-index: 5;
        background-color: #fff;
        padding: 5px;
        border: 1px solid #999;
      }
    </style>
      </head>
  <body>
    <script type="text/javascript"
      src="http://maps.googleapis.com/maps/api/js?key=AIzaSyAN0AoDw9FQx0RM5GmmUVdzQF-yf1ah9fU&sensor=FALSE">
    </script>
      <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
<% if user_signed_in? %>
<div id="panel">
    <span>Hello, <%= current_user.email %></span>
    <%= link_to 'sign out', destroy_user_session_path, :method => :delete %>
<%= form_for(Point.new) do |f| %>
<div class="field">
<%= f.text_field :coord, :value => '40.714224,-73.961452' %>
<%= f.text_field :usermail, :value => current_user.email,:readonly => true %>
</div>
<div class="actions">
    <%= f.submit 'Save Point' %>
<input type="button" value="Find Address" onclick="decodeAddress()"/>
          <input onclick="deleteMarkers()" type="button" value="Delete Markers"/>
<%= link_to 'your points', points_path %>
  </div>
<% end %>
    
<% else %>
    <%= link_to 'sign in', new_user_session_path %> ??? <%= link_to 'registration', new_user_registration_path %>
<% end %>
</div>
<br/>
    <div id="map_canvas">
    </div>
              <script type="text/javascript">
                  var location;
                  var map;
                  var geocoder;
                  var infowindow = new google.maps.InfoWindow();
                  var markers = [];
                  var container = document.createElement("div"); container.setAttribute("id", "list");
                  document.body.appendChild(container);

                  function initialize() {
                      geocoder = new google.maps.Geocoder();
                      var myLatlng = new google.maps.LatLng(-25.363882, 131.044922);
                      var mapOptions = {
                          zoom: 4,
                          center: myLatlng,
                          mapTypeId: 'roadmap'
                      }
                      map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);

                      google.maps.event.addListener(map, 'click', function (event) {
                          placeMarker(event.latLng);

                          //var newDiv = document.createElement("div");
                          //newDiv.innerHTML = event.latLng;
                          //my_div = document.getElementById("map_canvas");
                          //document.body.insertBefore(newDiv, my_div);
                      });
                  }

                  function decodeAddress() {
                      var input = document.getElementById('point_coord').value;
                      var latlngStr = input.split(",", 2);
                      var lat = parseFloat(latlngStr[0]);
                      var lng = parseFloat(latlngStr[1]);
                      var latlng = new google.maps.LatLng(lat, lng);
                      geocoder.geocode({ 'latLng': latlng }, function (results, status) {
                          if (status == google.maps.GeocoderStatus.OK) {
                              if (results[1]) {
                                  map.setZoom(11);
                                  marker = new google.maps.Marker({
                                      position: latlng,
                                      map: map
                                  });
                                  google.maps.event.addListener(marker, "click", function () {
                                      marker.setMap(null);
                                  });
                                  infowindow.setContent(results[1].formatted_address);
                                  infowindow.open(map, marker);
                                  markers.push(marker);
                              }
                          } else {
                              alert("Geocoder failed due to: " + status);
                          }
                      });
                  }

                  google.maps.event.addDomListener(window, 'load', initialize);

                  function placeMarker(location) {
                      var marker = new google.maps.Marker({
                          position: location,
                          map: map
                      });
                      google.maps.event.addListener(marker, "click", function () {
                          marker.setMap(null);
                      });
                      geocoder.geocode({ 'latLng': location }, function (results, status) {
                          if (status == google.maps.GeocoderStatus.OK) {
                              if (results[1]) {
                                  var newPar = document.createElement("p");
                                  var t = document.createTextNode(location + " " + results[1].formatted_address);
                                  newPar.appendChild(t);
                                  container.appendChild(newPar);
                              }
                          } else {
                              alert("Geocoder failed due to: " + status);
                          }
                      });
var mailinput = document.getElementById("point_coord");
                      var str = location.toString().replace("(","").replace(")","");
                      mailinput.value = str;

                      markers.push(marker);
                      map.setCenter(location);
                  }

                  function setAllMap(map) {
                      for (var i = 0; i < markers.length; i++) {
                          markers[i].setMap(map);
                      }
                  }

                  function deleteMarkers() {
                      setAllMap(null);
                      markers = [];
document.getElementById("point_coord").value = "";
                  }
    </script>
  </body>
</html>

app/views/points/_form.html.erb
<%= form_for(@point) do |f| %>
  <% if @point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@point.errors.count, "error") %> prohibited this point from being saved:</h2>

      <ul>
      <% @point.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :coord %><br>
    <%= f.text_field :coord %>
  </div>
  <div class="field">
    <%= f.label :usermail %><br>
    <%= f.text_field :usermail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/points/edit.html.erb
<h1>Editing point</h1>

<%= render 'form' %>

<%= link_to 'Show', @point %> |
<%= link_to 'Back', points_path %>

app/views/points/index.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head><title></title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
      <meta charset="utf-8"/>
    <style type="text/css">
      html { height: 100% }
      body { height: 100%; margin: 0; padding: 0 }
      #map_canvas { height: 80% }
      #panel {
        position: absolute;
        top: 5px;
        left: 50%;
        margin-left: -180px;
        z-index: 5;
        background-color: #fff;
        padding: 5px;
        border: 1px solid #999;
      }
    </style>
      </head>
  <body>
    <script type="text/javascript"
      src="http://maps.googleapis.com/maps/api/js?key=AIzaSyAN0AoDw9FQx0RM5GmmUVdzQF-yf1ah9fU&sensor=FALSE">
    </script>
      <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
<% if user_signed_in? %>
<div id="panel">
    <span>Hello, <%= current_user.email %></span>
    <%= link_to 'sign out', destroy_user_session_path, :method => :delete %>
<%= form_for(Point.new) do |f| %>
<div class="field">
<%= f.text_field :coord, :value => '40.714224,-73.961452' %>
<%= f.text_field :usermail, :value => current_user.email,:readonly => true %>
</div>
<div class="actions">
    <%= f.submit 'Save Point' %>
<input type="button" value="Find Address" onclick="decodeAddress()"/>
          <input onclick="deleteMarkers()" type="button" value="Delete Markers"/>
<%= link_to 'your points', points_path %>
  </div>
<% end %>
    
<% else %>
    <%= link_to 'sign in', new_user_session_path %> ??? <%= link_to 'registration', new_user_registration_path %>
<% end %>
</div>
<br/>
<table>
  <thead>
    <tr>
      <th>Coord</th>
      <th>Usermail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @points.each do |point| %>
      <tr>
        <td><%= point.coord %></td>
        <td><%= point.usermail %></td>
        <td><%= link_to 'Show', point %></td>
        <td><%= link_to 'Edit', edit_point_path(point) %></td>
        <td><%= link_to 'Destroy', point, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br/>
    <div id="map_canvas">
    </div><br/>
              <script type="text/javascript">
                  var location;
                  var map;
                  var geocoder;
                  var infowindow = new google.maps.InfoWindow();
                  var markers = [];
                  var container = document.createElement("div"); 
                  document.body.appendChild(container);
                  function initialize() {
                      geocoder = new google.maps.Geocoder();
                      var myLatlng = new google.maps.LatLng(-25.363882, 131.044922);
                      var mapOptions = {
                          zoom: 4,
                          center: myLatlng,
                          mapTypeId: 'roadmap'
                      }
                      map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
                      google.maps.event.addListener(map, 'click', function (event) {
                          placeMarker(event.latLng);

                          //var newDiv = document.createElement("div");
                          //newDiv.innerHTML = event.latLng;
                          //my_div = document.getElementById("map_canvas");
                          //document.body.insertBefore(newDiv, my_div);
                      });
                  }

                  function decodeAddress() {
                      var input = document.getElementById('point_coord').value;
                      var latlngStr = input.split(",", 2);
                      var lat = parseFloat(latlngStr[0]);
                      var lng = parseFloat(latlngStr[1]);
                      var latlng = new google.maps.LatLng(lat, lng);
                      geocoder.geocode({ 'latLng': latlng }, function (results, status) {
                          if (status == google.maps.GeocoderStatus.OK) {
                              if (results[1]) {
                                  map.setZoom(11);
                                  marker = new google.maps.Marker({
                                      position: latlng,
                                      map: map
                                  });
                                  google.maps.event.addListener(marker, "click", function () {
                                      marker.setMap(null);
                                  });
                                  infowindow.setContent(results[1].formatted_address);
                                  infowindow.open(map, marker);
                                  markers.push(marker);
                              }
                          } else {
                              alert("Geocoder failed due to: " + status);
                          }
                      });
                  }

                  google.maps.event.addDomListener(window, 'load', initialize);

                  function placeMarker(location) {
                      var marker = new google.maps.Marker({
                          position: location,
                          map: map
                      });
                      google.maps.event.addListener(marker, "click", function () {
                          marker.setMap(null);
                      });
                      geocoder.geocode({ 'latLng': location }, function (results, status) {
                          if (status == google.maps.GeocoderStatus.OK) {
                              if (results[1]) {
                                  var newPar = document.createElement("p");
                                  var t = document.createTextNode(location + " " + results[1].formatted_address);
                                  newPar.appendChild(t);
                                  container.appendChild(newPar);
                              }
                          } else {
                              alert("Geocoder failed due to: " + status);
                          }
                      });
var mailinput = document.getElementById("point_coord");
                      var str = location.toString().replace("(","").replace(")","");
                      mailinput.value = str;

                      markers.push(marker);
                      map.setCenter(location);
                  }

                  function setAllMap(map) {
                      for (var i = 0; i < markers.length; i++) {
                          markers[i].setMap(map);
                      }
                  }

                  function deleteMarkers() {
                      setAllMap(null);
                      markers = [];
document.getElementById("point_coord").value = "";
                  }
    </script>

<%= link_to 'New Point', new_point_path %>
  </body>
      </html>

app/views/points/new.html.erb
<h1>New point</h1>

<%= render 'form' %>

<%= link_to 'Back', points_path %>

app/views/points/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Coord:</strong>
  <%= @point.coord %>
</p>

<p>
  <strong>Usermail:</strong>
  <%= @point.usermail %>
</p>

<%= link_to 'Edit', edit_point_path(@point) %> |
<%= link_to 'Back', points_path %>